/** Normalize common CrossFit abbreviations before catalog fuzzy match. */
const MOVEMENT_ALIASES: Record<string, string> = {
  c2b: "Chest-to-Bar",
  ctb: "Chest-to-Bar",
  "chest to bar": "Chest-to-Bar",
  "chest-to-bar": "Chest-to-Bar",
  t2b: "Toes to Bar",
  "toes to bar": "Toes to Bar",
  "toes-to-bar": "Toes to Bar",
  ttb: "Toes to Bar",
  hspu: "Handstand Push-Up",
  "handstand push up": "Handstand Push-Up",
  "handstand push-up": "Handstand Push-Up",
  hsw: "Handstand Walk",
  bmu: "Bar Muscle-Up",
  "bar mu": "Bar Muscle-Up",
  "bar muscle up": "Bar Muscle-Up",
  mu: "Muscle-Up",
  "muscle up": "Muscle-Up",
  "pull up": "Pull-Up",
  "pull-up": "Pull-Up",
  "pull ups": "Pull-Up",
  "pull-ups": "Pull-Up",
  "push up": "Push-Up",
  "push-up": "Push-Up",
  "push ups": "Push-Up",
  "wall ball": "Wall Ball",
  "wall balls": "Wall Balls",
  wb: "Wall Ball",
  du: "Double Under",
  "double unders": "Double Under",
  "double under": "Double Under",
  su: "Single Under",
  "box jump": "Box Jump",
  "box jumps": "Box Jump",
  bj: "Box Jump",
  bjo: "Box Jump Over",
  "box jump over": "Box Jump Over",
  burpee: "Burpee",
  burpees: "Burpee",
  kbs: "Kettlebell Swing",
  "kb swing": "Kettlebell Swing",
  "american kb swing": "American Kettlebell Swing",
  "russian kb swing": "Russian Kettlebell Swing",
  sdhp: "Sumo Deadlift High Pull",
  ghd: "GHD Sit-Up",
  "ghd situp": "GHD Sit-Up",
  "ghd sit up": "GHD Sit-Up",
  "sit up": "Sit-Up",
  situp: "Sit-Up",
  "sit ups": "Sit-Up",
  "sit-ups": "Sit-Up",
  "devil press": "Devil Press",
  "devil presses": "Devil Press",
  "devils press": "Devil Press",
  "rope climb": "Rope Climb",
  run: "Run",
  row: "Row",
  "ski erg": "Ski Erg",
  "assault bike": "Assault Bike",
  "echo bike": "Echo Bike",
  "bike erg": "Bike Erg",
};

export function normalizeMovementAlias(raw: string): string {
  const key = raw.trim().toLowerCase();
  return MOVEMENT_ALIASES[key] ?? raw.trim();
}
